# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Auth'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'TicTacReflexToe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TicTacReflexToe

end
